### ISSUE TITLE
Updating three.js version?

### ISSUE THREAD

**Issue by mrspeaker** [antonkulaga/scala-js-facades#1]
Is there a process for moving to the latest three.js versions? The version included here is 68, but [latest is 70](https://github.com/mrdoob/three.js/releases) - and there are a few really big things in there (especially the addition of geometry's mergeMesh method and the new PlaneBufferGeometry).

Those guys move pretty quickly, it would be cool if there were some way to stay up to date - even if it was just amending things by hand. I was going to do try it out and submit a PR, but I figure I'd ask first to see if you have an automated process etc.

Thanks!

**Comment by antonkulaga** [comment]
Yes, PR is welcome. I am very busy this week :(
Do you think we should add some phantom/selenium tests? 

P.S. I am thinking about splitting scala-js-facades into separate libraries with their own examples and some selenium/phantomjs tests but could not find time for this yet.

**Comment by mrspeaker** [comment]
Yeah, I think splitting is a good idea!

**Comment by antonkulaga** [comment]
Now it has r71 version

**Comment by antonkulaga** [comment]
Threejs facade moved to https://github.com/antonkulaga/threejs-facade
