### ISSUE TITLE
Line mesh accepts LineDashedMaterial instead of LineBasicMaterial

### ISSUE THREAD

**Issue by mrspeaker** [antonkulaga/scala-js-facades#2]
Creating a line with LineBasicMaterial throws a type mismatch because [the this params](https://github.com/antonkulaga/scala-js-facades/blob/master/threejs/src/main/scala/org/denigma/threejs/threejs.scala#L1970):  it accepts `LineDashedMaterial` instead of `LIneBasicMaterial` (well, I guess it should accept both - but `LineBasicMaterial` is the defined type on the material property).

**Comment by mrspeaker** [comment]
Added a PR: https://github.com/antonkulaga/scala-js-facades/pull/6

**Comment by antonkulaga** [comment]
merged
