### ISSUE TITLE
HoverControls zoom doesn't work in Firefox

### ISSUE THREAD

**Issue by mrspeaker** [antonkulaga/scala-js-facades#3]
Zooming in firefox gives the console runtime error:

```
uncaught exception: scala.scalajs.runtime.UndefinedBehaviorError: 
An undefined behavior was detected: undefined is not an instance of java.lang.Integer
```

because of this line: https://github.com/antonkulaga/scala-js-facades/blob/master/threejs/src/main/scala/org/denigma/threejs/extensions/controls/HoverControls.scala#L246

because wheel.wheelData is undefined in firefox, it is true that `wheel.wheelDelta != 0`, so it tries to cast undefined as an int.

**Comment by antonkulaga** [comment]
Thanks for the report. I will check this weekend
