### ISSUE TITLE
Color class doesn't accept hex value param 

### ISSUE THREAD

**Issue by mrspeaker** [antonkulaga/scala-js-facades#4]
In three.js the Color accepts a parameter that is an "optional argument that sets initial color. Can be a hexadecimal or a CSS-style string, for example, "rgb(250, 0,0)", "rgb(100%,0%,0%)", "#ff0000", "#f00", or "red", or three arguments that represent color channels. " Is it possible to add these?

And if not, most three.js code uses new `new Color(0xffffff)` to define colors... it's possible to do new Color().setHex(0xffffff) but it's so common that it's ugly to have to do that everywhere. The types in scala accepts a Color as input, but in three.js it's idiomatic to use the color.copy(exitingColor) if you want to define a color from another one. Anyhoo... not important, just a lil' annoying!

**Comment by mrspeaker** [comment]
Derp, just need to add it to the facade. PR for this here: https://github.com/antonkulaga/scala-js-facades/pull/5

**Comment by antonkulaga** [comment]
Thank you for the PR, meged
